version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-gnosis}
      DB_USER: ${DB_USER:-vitalik}
      DB_PASSWORD: ${DB_PASSWORD:-wagmi}
      NODE_ENV: development
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-vitalik}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wagmi}
      POSTGRES_DB: ${DB_NAME:-gnosis}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
